FROM golang:1.24-alpine AS builder

COPY . /chat_server/chat/source

WORKDIR /chat_server/chat/source

RUN go mod download
RUN go build -o ./bin/chat_server  cmd/grpc_server/main.go


FROM alpine:latest

WORKDIR /root/

COPY --from=builder /chat_server/chat/source/bin/chat_server .

CMD ["./chat_server"]


